### ISSUE TITLE
Environment upgrade

### ISSUE THREAD

**Issue by nexussmart** [Samaritan1011001/proximity_plugin#1]
Hi,

Can you upgrade the environment of your plugin so that it is compatible with version 2.1.0 ?

Error :
Because *** depends on proximity_plugin >=1.0.0 which requires SDK version <2.0.0, version solving failed.

Thx

**Comment by UnCheon** [comment]
Please upgrade the environment of your plugin.

**Comment by Samaritan1011001** [comment]
I have upgraded the master and also the package on pub. Please do check and let me know. 
@UnCheon @nexussmart
